# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Install mkdocs
        run: pip install mkdocs
        
      - name: Install material theme
        run: pip install mkdocs-material

      - name: Setup directory stucture for mkdocs
        run: |
          cd ..
          git clone https://github.com/upslopeio/ibm-cloud-garage-training-mkdocs.git
          ls
          ls ibm-cloud-garage-training-mkdocs
        
